from __future__ import annotations

from dataclasses import dataclass


STRONG_SENDER_TYPES = {"primary", "email"}
LINK_TRUST_TYPES = {"primary", "email", "redirect", "asset", "infrastructure"}
WEAK_TRUST_TYPES = {"redirect", "asset", "infrastructure"}


@dataclass(frozen=True)
class DomainTrustRecord:
    brand: str
    domain: str
    trust_type: str
    notes: str = ""

    @property
    def strong_sender(self) -> bool:
        return self.trust_type in STRONG_SENDER_TYPES

    @property
    def weak(self) -> bool:
        return self.trust_type in WEAK_TRUST_TYPES


TRUST_RECORDS: tuple[DomainTrustRecord, ...] = tuple(
    DomainTrustRecord(brand, domain.lower(), trust_type, notes)
    for brand, domain, trust_type, notes in [
        ("Apple", "apple.com", "primary", "Official Apple domain"),
        ("Apple", "icloud.com", "primary", "Official iCloud services domain"),
        ("Apple", "me.com", "email", "Legacy Apple email domain"),
        ("Apple", "mac.com", "email", "Legacy Apple email domain"),
        ("Apple", "mzstatic.com", "asset", "Apple static assets"),
        ("Apple", "cdn-apple.com", "asset", "Apple CDN"),
        ("Apple", "icloud-content.com", "asset", "iCloud content delivery"),
        ("Apple", "itunes.com", "primary", "Legacy iTunes domain"),
        ("Apple", "apple.news", "redirect", "Apple News short link"),
        ("Amazon", "amazon.com", "primary", "Official Amazon domain"),
        ("Amazon", "amazon.co.uk", "primary", "Official Amazon UK domain"),
        ("Amazon", "amazon.ca", "primary", "Official Amazon Canada domain"),
        ("Amazon", "aws.amazon.com", "primary", "Official AWS portal"),
        ("Amazon", "amzn.to", "redirect", "Official Amazon shortener"),
        ("Amazon", "images-amazon.com", "asset", "Amazon static images"),
        ("Amazon", "ssl-images-amazon.com", "asset", "Amazon secure static images"),
        ("AWS", "amazonaws.com", "infrastructure", "AWS hosted infrastructure"),
        ("AWS", "cloudfront.net", "infrastructure", "AWS CloudFront CDN"),
        ("Meta", "facebook.com", "primary", "Official Facebook domain"),
        ("Meta", "meta.com", "primary", "Official Meta domain"),
        ("Meta", "fb.com", "redirect", "Official Facebook short domain"),
        ("Meta", "fb.me", "redirect", "Official Facebook shortener"),
        ("Meta", "fbsbx.com", "asset", "Facebook assets"),
        ("Meta", "fbcdn.net", "asset", "Facebook CDN"),
        ("Meta", "instagram.com", "primary", "Official Instagram domain"),
        ("Meta", "cdninstagram.com", "asset", "Instagram CDN"),
        ("Meta", "whatsapp.com", "primary", "Official WhatsApp domain"),
        ("Meta", "whatsapp.net", "infrastructure", "WhatsApp backend network"),
        ("Google", "google.com", "primary", "Official Google domain"),
        ("Google", "gmail.com", "email", "Gmail domain"),
        ("Google", "accounts.google.com", "primary", "Google account portal"),
        ("Google", "workspace.google.com", "primary", "Google Workspace portal"),
        ("Google", "admin.google.com", "primary", "Google Workspace admin"),
        ("Google", "youtube.com", "primary", "Official YouTube domain"),
        ("Google", "youtu.be", "redirect", "Official YouTube shortener"),
        ("Google", "ytimg.com", "asset", "YouTube thumbnail hosting"),
        ("Google", "googlevideo.com", "asset", "YouTube video infrastructure"),
        ("Google", "gstatic.com", "asset", "Google static content"),
        ("Google", "googleusercontent.com", "asset", "Google user content"),
        ("Google", "ggpht.com", "asset", "Google profile/photo images"),
        ("Google", "appspot.com", "infrastructure", "Google App Engine apps"),
        ("Google", "recaptcha.net", "infrastructure", "Official reCAPTCHA"),
        ("Google", "googletagmanager.com", "asset", "Google Tag Manager"),
        ("Google", "google-analytics.com", "asset", "Google Analytics"),
        ("Microsoft", "microsoft.com", "primary", "Official Microsoft domain"),
        ("Microsoft", "office.com", "primary", "Microsoft Office portal"),
        ("Microsoft", "office365.com", "infrastructure", "Office 365 services"),
        ("Microsoft", "outlook.com", "email", "Outlook email domain"),
        ("Microsoft", "outlook.office.com", "primary", "Outlook Web Access"),
        ("Microsoft", "live.com", "primary", "Microsoft Live services"),
        ("Microsoft", "skype.com", "primary", "Official Skype domain"),
        ("Microsoft", "sfx.ms", "asset", "Microsoft Skype static assets"),
        ("Microsoft", "windows.net", "infrastructure", "Azure core network"),
        ("Microsoft", "azure.com", "primary", "Official Azure domain"),
        ("Microsoft", "azureedge.net", "infrastructure", "Azure CDN"),
        ("Microsoft", "microsoftonline.com", "infrastructure", "Microsoft 365 login"),
        ("Microsoft", "msauth.net", "infrastructure", "Microsoft MFA"),
        ("Microsoft", "sharepoint.com", "primary", "SharePoint core domain"),
        ("Microsoft", "bing.com", "primary", "Microsoft Bing"),
        ("Microsoft", "msn.com", "primary", "Microsoft Network portal"),
        ("LinkedIn", "linkedin.com", "primary", "Official LinkedIn domain"),
        ("LinkedIn", "lnkd.in", "redirect", "Official LinkedIn short link"),
        ("LinkedIn", "licdn.com", "asset", "LinkedIn CDN and assets"),
        ("LinkedIn", "e.linkedin.com", "email", "LinkedIn email sending domain"),
        ("X", "twitter.com", "primary", "Legacy Twitter domain"),
        ("X", "x.com", "primary", "Official X domain"),
        ("X", "t.co", "redirect", "Official X shortener"),
        ("X", "twimg.com", "asset", "X media hosting"),
        ("Netflix", "netflix.com", "primary", "Official Netflix domain"),
        ("Netflix", "nflxext.com", "asset", "Netflix static extension assets"),
        ("Netflix", "nflximg.com", "asset", "Netflix image hosting"),
        ("Netflix", "nflximg.net", "asset", "Netflix image network"),
        ("Netflix", "nflxso.net", "asset", "Netflix streaming objects"),
        ("GitHub", "github.com", "primary", "Official GitHub domain"),
        ("GitHub", "githubusercontent.com", "asset", "GitHub user content"),
        ("GitHub", "github.io", "infrastructure", "GitHub Pages"),
        ("GitLab", "gitlab.com", "primary", "Official GitLab domain"),
        ("GitLab", "gitlab.io", "infrastructure", "GitLab Pages"),
        ("Atlassian", "atlassian.com", "primary", "Official Atlassian domain"),
        ("Atlassian", "bitbucket.org", "primary", "Official Bitbucket domain"),
        ("Atlassian", "trello.com", "primary", "Official Trello domain"),
        ("Atlassian", "atlassian.net", "infrastructure", "Atlassian cloud instances"),
        ("Slack", "slack.com", "primary", "Official Slack domain"),
        ("Slack", "slack-edge.com", "asset", "Slack CDN"),
        ("Slack", "slack-core.com", "infrastructure", "Slack backend API"),
        ("Slack", "slack-msgs.com", "asset", "Slack message assets"),
        ("Slack", "slack-files.com", "asset", "Slack uploaded files"),
        ("Salesforce", "salesforce.com", "primary", "Official Salesforce domain"),
        ("Salesforce", "force.com", "infrastructure", "Salesforce apps"),
        ("Salesforce", "salesforce-communities.com", "infrastructure", "Salesforce communities"),
        ("Salesforce", "sfdcstatic.com", "asset", "Salesforce static assets"),
        ("PayPal", "paypal.com", "primary", "Official PayPal domain"),
        ("PayPal", "paypalobjects.com", "asset", "PayPal static assets"),
        ("PayPal", "paypal.me", "redirect", "PayPal payment links"),
        ("PayPal", "venmo.com", "primary", "Official Venmo domain"),
        ("PayPal", "braintreegateway.com", "infrastructure", "Braintree payment gateway"),
        ("Stripe", "stripe.com", "primary", "Official Stripe domain"),
        ("Stripe", "b.stripe.com", "asset", "Stripe fraud tracking"),
        ("Stripe", "js.stripe.com", "asset", "Stripe JS library"),
        ("Stripe", "stripe.network", "infrastructure", "Stripe backend routing"),
        ("Spotify", "spotify.com", "primary", "Official Spotify domain"),
        ("Spotify", "spoti.fi", "redirect", "Official Spotify shortener"),
        ("Spotify", "scdn.co", "asset", "Spotify CDN"),
        ("Spotify", "spotifycdn.com", "asset", "Spotify secondary CDN"),
        ("Pinterest", "pinterest.com", "primary", "Official Pinterest domain"),
        ("Pinterest", "pin.it", "redirect", "Official Pinterest shortener"),
        ("Pinterest", "pinimg.com", "asset", "Pinterest image hosting"),
        ("Reddit", "reddit.com", "primary", "Official Reddit domain"),
        ("Reddit", "redd.it", "redirect", "Official Reddit shortener"),
        ("Reddit", "redditstatic.com", "asset", "Reddit static assets"),
        ("Reddit", "reddmedia.com", "asset", "Reddit media hosting"),
        ("Twitch", "twitch.tv", "primary", "Official Twitch domain"),
        ("Twitch", "ttvnw.net", "asset", "Twitch video network"),
        ("Twitch", "jtvnw.net", "asset", "Twitch legacy assets"),
        ("Adobe", "adobe.com", "primary", "Official Adobe domain"),
        ("Adobe", "typekit.net", "asset", "Adobe Fonts"),
        ("Adobe", "adobelogin.com", "infrastructure", "Adobe login endpoint"),
        ("Adobe", "adobe-photos.com", "asset", "Adobe photo assets"),
        ("Adobe", "adobesc.com", "asset", "Adobe Scene7 hosting"),
        ("Dropbox", "dropbox.com", "primary", "Official Dropbox domain"),
        ("Dropbox", "paper.dropbox.com", "primary", "Dropbox Paper"),
        ("Dropbox", "dropboxstatic.com", "asset", "Dropbox static assets"),
        ("Dropbox", "dropboxusercontent.com", "asset", "Dropbox file delivery"),
        ("Dropbox", "db.tt", "redirect", "Official Dropbox shortener"),
        ("Box", "box.com", "primary", "Official Box domain"),
        ("Box", "boxcloud.com", "infrastructure", "Box storage backend"),
        ("Yahoo", "yahoo.com", "primary", "Official Yahoo domain"),
        ("Yahoo", "yimg.com", "asset", "Yahoo CDN"),
        ("Yahoo", "yahoo.co.jp", "primary", "Yahoo Japan"),
        ("Shopify", "shopify.com", "primary", "Official Shopify domain"),
        ("Shopify", "myshopify.com", "infrastructure", "Shopify merchant stores"),
        ("Shopify", "cdn.shopify.com", "asset", "Shopify CDN"),
        ("Zoom", "zoom.us", "primary", "Official Zoom domain"),
        ("Zoom", "zoom.com", "redirect", "Secondary Zoom domain"),
        ("Zoom", "zoomgov.com", "primary", "Zoom Government"),
        ("Zoom", "zoom.com.cn", "primary", "Zoom China"),
        ("Discord", "discord.com", "primary", "Official Discord domain"),
        ("Discord", "discord.gg", "redirect", "Discord invite shortlink"),
        ("Discord", "discordapp.com", "primary", "Legacy Discord domain"),
        ("Discord", "discordapp.net", "asset", "Discord CDN"),
        ("TikTok", "tiktok.com", "primary", "Official TikTok domain"),
        ("TikTok", "tiktokcdn.com", "asset", "TikTok CDN"),
        ("TikTok", "ttwstatic.com", "asset", "TikTok static assets"),
        ("ByteDance", "bytedance.com", "primary", "Official ByteDance domain"),
        ("ByteDance", "pstatp.com", "asset", "ByteDance asset network"),
        ("Cloudflare", "cloudflare.com", "primary", "Official Cloudflare domain"),
        ("Cloudflare", "cloudflarejs.com", "asset", "Cloudflare scripts"),
        ("Cloudflare", "cdnjs.com", "asset", "Cloudflare CDNJS"),
        ("Cloudflare", "pages.dev", "infrastructure", "Cloudflare Pages"),
        ("Cloudflare", "cloudflare-gateway.com", "infrastructure", "Cloudflare gateway"),
        ("Cloudflare", "1.1.1.1", "infrastructure", "Cloudflare DNS"),
        ("Fastly", "fastly.com", "primary", "Official Fastly domain"),
        ("Fastly", "fastly.net", "infrastructure", "Fastly CDN endpoints"),
        ("Vimeo", "vimeo.com", "primary", "Official Vimeo domain"),
        ("Vimeo", "vimeocdn.com", "asset", "Vimeo CDN"),
        ("Canva", "canva.com", "primary", "Official Canva domain"),
        ("Canva", "canva-apps.com", "infrastructure", "Canva embedded apps"),
        ("Canva", "canvacdn.com", "asset", "Canva CDN"),
        ("Chase", "chase.com", "primary", "Official Chase domain"),
        ("Chase", "jpmorgan.com", "primary", "JPMorgan domain"),
        ("Bank of America", "bankofamerica.com", "primary", "Official BofA domain"),
        ("Bank of America", "bofa.com", "redirect", "BofA short domain"),
        ("Wells Fargo", "wellsfargo.com", "primary", "Official Wells Fargo domain"),
        ("Citibank", "citi.com", "primary", "Official Citibank domain"),
        ("Citibank", "citibank.com", "primary", "Secondary Citibank domain"),
        ("American Express", "americanexpress.com", "primary", "Official Amex domain"),
        ("American Express", "amex.com", "redirect", "Amex short domain"),
        ("American Express", "aexp-static.com", "asset", "Amex assets"),
        ("Capital One", "capitalone.com", "primary", "Official Capital One domain"),
        ("Visa", "visa.com", "primary", "Official Visa domain"),
        ("Visa", "visa.com.hk", "primary", "Visa Hong Kong"),
        ("Visa", "visa.co.in", "primary", "Visa India"),
        ("Mastercard", "mastercard.com", "primary", "Official Mastercard domain"),
        ("Mastercard", "mastercard.us", "primary", "Mastercard US"),
        ("Mastercard", "priceless.com", "primary", "Mastercard rewards"),
        ("Discover", "discover.com", "primary", "Official Discover domain"),
        ("Block", "squareup.com", "primary", "Official Square domain"),
        ("Block", "cash.app", "primary", "Official Cash App domain"),
        ("Walmart", "walmart.com", "primary", "Official Walmart domain"),
        ("Walmart", "wmt.co", "redirect", "Walmart short link"),
        ("Walmart", "walmartimages.com", "asset", "Walmart image hosting"),
        ("Target", "target.com", "primary", "Official Target domain"),
        ("eBay", "ebay.com", "primary", "Official eBay domain"),
        ("eBay", "ebayimg.com", "asset", "eBay image hosting"),
        ("eBay", "ebayrtm.com", "asset", "eBay marketing assets"),
        ("Etsy", "etsy.com", "primary", "Official Etsy domain"),
        ("Etsy", "etsystatic.com", "asset", "Etsy static assets"),
        ("Home Depot", "homedepot.com", "primary", "Official Home Depot domain"),
        ("Best Buy", "bestbuy.com", "primary", "Official Best Buy domain"),
        ("Costco", "costco.com", "primary", "Official Costco domain"),
        ("Uber", "uber.com", "primary", "Official Uber domain"),
        ("Uber", "ubereats.com", "primary", "Official Uber Eats domain"),
        ("Lyft", "lyft.com", "primary", "Official Lyft domain"),
        ("Airbnb", "airbnb.com", "primary", "Official Airbnb domain"),
        ("Airbnb", "muscache.com", "asset", "Airbnb media cache"),
        ("Booking", "booking.com", "primary", "Official Booking.com domain"),
        ("Expedia", "expedia.com", "primary", "Official Expedia domain"),
        ("Delta", "delta.com", "primary", "Official Delta domain"),
        ("United", "united.com", "primary", "Official United Airlines domain"),
        ("American Airlines", "aa.com", "primary", "Official American Airlines domain"),
        ("Okta", "okta.com", "primary", "Official Okta domain"),
        ("Okta", "oktacdn.com", "asset", "Okta CDN"),
        ("Auth0", "auth0.com", "primary", "Official Auth0 domain"),
        ("Duo", "duosecurity.com", "primary", "Official Duo Security domain"),
        ("CrowdStrike", "crowdstrike.com", "primary", "Official CrowdStrike domain"),
        ("Palo Alto Networks", "paloaltonetworks.com", "primary", "Official Palo Alto domain"),
        ("Fortinet", "fortinet.com", "primary", "Official Fortinet domain"),
        ("Heroku", "heroku.com", "primary", "Official Heroku domain"),
        ("Heroku", "herokuapp.com", "infrastructure", "Heroku hosted apps"),
        ("Vercel", "vercel.com", "primary", "Official Vercel domain"),
        ("Vercel", "vercel.app", "infrastructure", "Vercel hosted apps"),
        ("Netlify", "netlify.com", "primary", "Official Netlify domain"),
        ("Netlify", "netlify.app", "infrastructure", "Netlify hosted apps"),
        ("DigitalOcean", "digitalocean.com", "primary", "Official DigitalOcean domain"),
        ("Docker", "docker.com", "primary", "Official Docker domain"),
        ("Docker", "docker.io", "infrastructure", "Docker Hub registry"),
        ("Disney", "disney.com", "primary", "Official Disney domain"),
        ("Disney", "disneyplus.com", "primary", "Disney+ domain"),
        ("Disney", "bamgrid.com", "infrastructure", "Disney streaming backend"),
        ("NYT", "nytimes.com", "primary", "Official New York Times domain"),
        ("BBC", "bbc.com", "primary", "Official BBC domain"),
        ("BBC", "bbc.co.uk", "primary", "Official BBC UK domain"),
        ("BBC", "bbci.co.uk", "asset", "BBC infrastructure and assets"),
        ("CNN", "cnn.com", "primary", "Official CNN domain"),
        ("CNN", "cnn.io", "redirect", "CNN shortlink"),
        ("Akamai", "akamai.net", "infrastructure", "Akamai CDN"),
        ("Akamai", "akamaiedge.net", "infrastructure", "Akamai edge routing"),
        ("Akamai", "akamaihd.net", "asset", "Akamai media delivery"),
        ("Akamai", "edgesuite.net", "infrastructure", "Akamai edge network"),
        ("IBM", "ibm.com", "primary", "Official IBM domain"),
        ("IBM", "appdomain.cloud", "infrastructure", "IBM Cloud apps"),
        ("Oracle", "oracle.com", "primary", "Official Oracle domain"),
        ("Oracle", "oraclecloud.com", "infrastructure", "Oracle Cloud"),
        ("Cisco", "cisco.com", "primary", "Official Cisco domain"),
        ("Cisco", "webex.com", "primary", "Official Webex domain"),
        ("Webex", "webexconnect.com", "infrastructure", "Webex messaging"),
        ("Intuit", "intuit.com", "primary", "Official Intuit domain"),
        ("Intuit", "turbotax.com", "primary", "Official TurboTax domain"),
        ("Intuit", "quickbooks.com", "primary", "Official QuickBooks domain"),
        ("Zillow", "zillow.com", "primary", "Official Zillow domain"),
        ("Zillow", "zillowstatic.com", "asset", "Zillow assets"),
        ("Twilio", "twilio.com", "primary", "Official Twilio domain"),
        ("Twilio", "sendgrid.net", "email", "SendGrid delivery network"),
        ("Mailchimp", "mailchimp.com", "primary", "Official Mailchimp domain"),
        ("Mailchimp", "list-manage.com", "infrastructure", "Mailchimp list management"),
        ("Mailchimp", "rs6.net", "email", "Legacy email infrastructure"),
        ("HubSpot", "hubspot.com", "primary", "Official HubSpot domain"),
        ("HubSpot", "hsforms.com", "infrastructure", "HubSpot forms"),
        ("HubSpot", "hs-scripts.com", "asset", "HubSpot scripts"),
        ("Notion", "notion.so", "primary", "Official Notion domain"),
        ("Notion", "notion.site", "infrastructure", "Notion public sites"),
        ("Figma", "figma.com", "primary", "Official Figma domain"),
        ("DocuSign", "docusign.com", "primary", "Official DocuSign domain"),
        ("DocuSign", "docusign.net", "infrastructure", "DocuSign signing platform"),
        ("ServiceNow", "servicenow.com", "primary", "Official ServiceNow domain"),
        ("Zendesk", "zendesk.com", "primary", "Official Zendesk domain"),
        ("Zendesk", "zdcdn.com", "asset", "Zendesk static assets"),
        ("Workday", "workday.com", "primary", "Official Workday domain"),
        ("Workday", "myworkday.com", "infrastructure", "Workday employee portal"),
        ("Stack Overflow", "stackoverflow.com", "primary", "Official Stack Overflow domain"),
        ("Stack Overflow", "sstatic.net", "asset", "Stack Overflow assets"),
        ("Quora", "quora.com", "primary", "Official Quora domain"),
        ("Medium", "medium.com", "primary", "Official Medium domain"),
        ("NVIDIA", "nvidia.com", "primary", "Official NVIDIA domain"),
        ("Intel", "intel.com", "primary", "Official Intel domain"),
        ("AMD", "amd.com", "primary", "Official AMD domain"),
        ("Qualcomm", "qualcomm.com", "primary", "Official Qualcomm domain"),
        ("Tesla", "tesla.com", "primary", "Official Tesla domain"),
        ("Ford", "ford.com", "primary", "Official Ford domain"),
        ("Toyota", "toyota.com", "primary", "Official Toyota domain"),
        ("FedEx", "fedex.com", "primary", "Official FedEx domain"),
        ("UPS", "ups.com", "primary", "Official UPS domain"),
        ("DHL", "dhl.com", "primary", "Official DHL domain"),
        ("United States Government", "gov", "primary", "US government TLD"),
        ("United States Government", "usa.gov", "primary", "US government portal"),
        ("United Kingdom Government", "gov.uk", "primary", "UK government portal"),
        ("European Union", "europa.eu", "primary", "European Union portal"),
        ("Education Sector", "edu", "primary", "US higher education TLD"),
        ("Harvard University", "harvard.edu", "primary", "Harvard"),
        ("MIT", "mit.edu", "primary", "MIT"),
        ("Stanford University", "stanford.edu", "primary", "Stanford"),
        ("DigiCert", "digicert.com", "infrastructure", "Certificate Authority"),
        ("Let's Encrypt", "letsencrypt.org", "infrastructure", "Certificate Authority"),
        ("GlobalSign", "globalsign.com", "infrastructure", "Certificate Authority"),
        ("Sectigo", "sectigo.com", "infrastructure", "Certificate Authority"),
        ("HSBC", "hsbc.com", "primary", "Official HSBC domain"),
        ("HSBC", "hsbc.co.uk", "primary", "Official HSBC UK domain"),
        ("Barclays", "barclays.co.uk", "primary", "Official Barclays domain"),
        ("Goldman Sachs", "gs.com", "primary", "Official Goldman Sachs domain"),
        ("Morgan Stanley", "morganstanley.com", "primary", "Official Morgan Stanley domain"),
        ("Charles Schwab", "schwab.com", "primary", "Official Schwab domain"),
        ("Fidelity", "fidelity.com", "primary", "Official Fidelity domain"),
        ("Vanguard", "vanguard.com", "primary", "Official Vanguard domain"),
        ("Robinhood", "robinhood.com", "primary", "Official Robinhood domain"),
        ("Coinbase", "coinbase.com", "primary", "Official Coinbase domain"),
        ("Binance", "binance.com", "primary", "Official Binance domain"),
        ("Kraken", "kraken.com", "primary", "Official Kraken domain"),
        ("Commonwealth Bank", "commbank.com.au", "primary", "Main CBA banking portal"),
        ("Commonwealth Bank", "cba.com.au", "redirect", "CBA short redirect"),
        ("Commonwealth Bank", "netbank.com.au", "primary", "CBA NetBank portal"),
        ("Westpac", "westpac.com.au", "primary", "Main Westpac portal"),
        ("Westpac", "bankofmelbourne.com.au", "primary", "Westpac subsidiary"),
        ("Westpac", "banksa.com.au", "primary", "Westpac subsidiary"),
        ("Westpac", "stgeorge.com.au", "primary", "Westpac subsidiary"),
        ("ANZ", "anz.com.au", "primary", "Main ANZ banking portal"),
        ("ANZ", "anz.com", "primary", "Global ANZ domain"),
        ("NAB", "nab.com.au", "primary", "Main NAB portal"),
        ("NAB", "ubank.com.au", "primary", "NAB digital brand"),
        ("Macquarie Bank", "macquarie.com.au", "primary", "Macquarie Bank AU"),
        ("Macquarie Bank", "macquarie.com", "primary", "Macquarie global"),
        ("Bendigo Bank", "bendigobank.com.au", "primary", "Bendigo Bank"),
        ("Bendigo Bank", "up.com.au", "primary", "Up Bank"),
        ("Suncorp", "suncorp.com.au", "primary", "Suncorp"),
        ("Bank of Queensland", "boq.com.au", "primary", "BOQ"),
        ("ING Australia", "ing.com.au", "primary", "ING Australia"),
        ("Australian Government", "australia.gov.au", "primary", "Federal portal"),
        ("myGov", "my.gov.au", "primary", "Official myGov portal"),
        ("ATO", "ato.gov.au", "primary", "Australian Taxation Office"),
        ("Services Australia", "servicesaustralia.gov.au", "primary", "Centrelink/Medicare"),
        ("Medicare", "medicare.com.au", "redirect", "Medicare redirect"),
        ("Health Australia", "health.gov.au", "primary", "Department of Health"),
        ("Home Affairs Australia", "homeaffairs.gov.au", "primary", "Home Affairs"),
        ("ASIC", "asic.gov.au", "primary", "Australian Securities and Investments Commission"),
        ("ABN Lookup", "abr.business.gov.au", "primary", "Official ABN lookup"),
        ("NSW Government", "nsw.gov.au", "primary", "NSW Government"),
        ("VIC Government", "vic.gov.au", "primary", "Victoria Government"),
        ("QLD Government", "qld.gov.au", "primary", "Queensland Government"),
        ("Service NSW", "service.nsw.gov.au", "primary", "Service NSW"),
        ("Service VIC", "service.vic.gov.au", "primary", "Service Victoria"),
        ("Telstra", "telstra.com.au", "primary", "Telstra AU"),
        ("Telstra", "telstra.com", "redirect", "Telstra global redirect"),
        ("Optus", "optus.com.au", "primary", "Optus AU"),
        ("Optus", "yesoptus.com.au", "redirect", "Legacy Optus portal"),
        ("TPG", "tpg.com.au", "primary", "TPG"),
        ("Woolworths", "woolworths.com.au", "primary", "Woolworths"),
        ("Woolworths", "woolies.com.au", "redirect", "Woolworths short domain"),
        ("Everyday Rewards", "everydayrewards.com.au", "primary", "Woolworths rewards"),
        ("Coles", "coles.com.au", "primary", "Coles"),
        ("Coles", "flybuys.com.au", "primary", "Flybuys"),
        ("Bunnings", "bunnings.com.au", "primary", "Bunnings"),
        ("Kmart", "kmart.com.au", "primary", "Kmart AU"),
        ("JB Hi-Fi", "jbhifi.com.au", "primary", "JB Hi-Fi"),
        ("Australia Post", "auspost.com.au", "primary", "Australia Post"),
        ("Australia Post", "mypost.com.au", "infrastructure", "Australia Post tracking/account"),
        ("Qantas", "qantas.com", "primary", "Qantas"),
        ("Qantas", "qantas.com.au", "redirect", "Qantas AU redirect"),
        ("Virgin Australia", "virginaustralia.com", "primary", "Virgin Australia"),
        ("University of Sydney", "sydney.edu.au", "primary", "USyd"),
        ("University of Melbourne", "unimelb.edu.au", "primary", "UniMelb"),
        ("UNSW", "unsw.edu.au", "primary", "UNSW"),
        ("Monash University", "monash.edu", "primary", "Monash"),
        ("Monash University", "monash.edu.au", "redirect", "Monash AU redirect"),
        ("ANU", "anu.edu.au", "primary", "Australian National University"),
        ("UQ", "uq.edu.au", "primary", "University of Queensland"),
        ("RMIT", "rmit.edu.au", "primary", "RMIT"),
        ("AGL Energy", "agl.com.au", "primary", "AGL"),
        ("Origin Energy", "originenergy.com.au", "primary", "Origin Energy"),
        ("EnergyAustralia", "energyaustralia.com.au", "primary", "EnergyAustralia"),
        ("Sydney Water", "sydneywater.com.au", "primary", "Sydney Water"),
        ("Bupa", "bupa.com.au", "primary", "Bupa AU"),
        ("Medibank", "medibank.com.au", "primary", "Medibank"),
        ("Realestate.com.au", "realestate.com.au", "primary", "Property portal"),
        ("Domain", "domain.com.au", "primary", "Property portal"),
        ("Indeed", "indeed.com", "primary", "Official Indeed domain"),
        ("Indeed", "match.indeed.com", "email", "Indeed job alert sender"),
    ]
)

TRUST_BY_DOMAIN = {record.domain: record for record in TRUST_RECORDS}


def normalize_lookup_domain(domain: str | None) -> str:
    return (domain or "").lower().strip().removeprefix("www.").strip(".")


def trust_record_for_domain(domain: str | None) -> DomainTrustRecord | None:
    normalized = normalize_lookup_domain(domain)
    if not normalized:
        return None
    labels = normalized.split(".")
    for index in range(len(labels)):
        candidate = ".".join(labels[index:])
        if candidate in TRUST_BY_DOMAIN:
            return TRUST_BY_DOMAIN[candidate]
    return None


def is_strong_sender_domain(domain: str | None) -> bool:
    record = trust_record_for_domain(domain)
    return bool(record and record.strong_sender)


def trusted_brand_for_domain(domain: str | None, *, sender_context: bool = True) -> str | None:
    record = trust_record_for_domain(domain)
    if not record:
        return None
    if sender_context and not record.strong_sender:
        return None
    return record.brand

